package com.kitchenledger.service;

import com.kitchenledger.config.AppProperties;
import com.kitchenledger.web.error.BadRequestException;
import com.kitchenledger.web.error.NotFoundException;
import jakarta.annotation.PostConstruct;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.Locale;
import java.util.UUID;
import java.util.regex.Pattern;

/**
 * Stores uploaded images outside the classpath. Format is decided by magic bytes rather than
 * the client-supplied name or content type, so a renamed script can never be stored or served
 * as an image, and SVG (which can carry script) is rejected outright.
 */
@Service
public class ImageStorageService {

    /** Keys are generated by this class; the pattern is re-checked on read to block traversal. */
    private static final Pattern SAFE_KEY = Pattern.compile("[0-9a-f]{2}/[0-9a-f]{32}\\.(jpg|png|webp|avif)");

    private static final byte[] JPEG = {(byte) 0xFF, (byte) 0xD8, (byte) 0xFF};
    private static final byte[] PNG = {(byte) 0x89, 'P', 'N', 'G', 0x0D, 0x0A, 0x1A, 0x0A};
    private static final byte[] RIFF = {'R', 'I', 'F', 'F'};
    private static final byte[] WEBP = {'W', 'E', 'B', 'P'};
    private static final byte[] FTYP = {'f', 't', 'y', 'p'};

    private final Path root;
    private final long maxBytes;

    public ImageStorageService(AppProperties properties) {
        this.root = Paths.get(properties.storage().uploadDir()).toAbsolutePath().normalize();
        this.maxBytes = properties.storage().maxImageBytes();
    }

    @PostConstruct
    void ensureRoot() throws IOException {
        Files.createDirectories(root);
    }

    public String store(MultipartFile file) {
        if (file == null || file.isEmpty()) {
            throw new BadRequestException("No image supplied");
        }
        if (file.getSize() > maxBytes) {
            throw new BadRequestException("Image exceeds the maximum allowed size");
        }

        byte[] header = readHeader(file);
        String extension = detectExtension(header)
                .orElseThrow(() -> new BadRequestException("Unsupported image format; use JPEG, PNG, WebP or AVIF"));

        String id = UUID.randomUUID().toString().replace("-", "");
        String key = id.substring(0, 2) + "/" + id + "." + extension;
        Path target = resolve(key);

        try {
            Files.createDirectories(target.getParent());
            try (InputStream in = file.getInputStream()) {
                Files.copy(in, target);
            }
        } catch (IOException ex) {
            throw new IllegalStateException("Could not store image", ex);
        }
        return key;
    }

    public Path load(String key) {
        Path path = resolve(key);
        if (!Files.isRegularFile(path)) {
            throw new NotFoundException("Image not found");
        }
        return path;
    }

    public void deleteQuietly(String key) {
        if (key == null || !SAFE_KEY.matcher(key).matches()) {
            return;
        }
        try {
            Files.deleteIfExists(resolve(key));
        } catch (IOException ignored) {
            // A leftover file is harmless; failing the request would not be.
        }
    }

    public String contentType(String key) {
        String extension = key.substring(key.lastIndexOf('.') + 1).toLowerCase(Locale.ROOT);
        return switch (extension) {
            case "png" -> "image/png";
            case "webp" -> "image/webp";
            case "avif" -> "image/avif";
            default -> "image/jpeg";
        };
    }

    private Path resolve(String key) {
        if (key == null || !SAFE_KEY.matcher(key).matches()) {
            throw new BadRequestException("Invalid image key");
        }
        Path resolved = root.resolve(key).normalize();
        if (!resolved.startsWith(root)) {
            throw new BadRequestException("Invalid image key");
        }
        return resolved;
    }

    private byte[] readHeader(MultipartFile file) {
        try (InputStream in = file.getInputStream()) {
            return in.readNBytes(16);
        } catch (IOException ex) {
            throw new BadRequestException("Could not read the uploaded file");
        }
    }

    private java.util.Optional<String> detectExtension(byte[] header) {
        if (startsWith(header, JPEG)) {
            return java.util.Optional.of("jpg");
        }
        if (startsWith(header, PNG)) {
            return java.util.Optional.of("png");
        }
        if (startsWith(header, RIFF) && regionMatches(header, 8, WEBP)) {
            return java.util.Optional.of("webp");
        }
        if (regionMatches(header, 4, FTYP)) {
            String brand = new String(header, 8, 4, java.nio.charset.StandardCharsets.US_ASCII);
            if (brand.startsWith("avif") || brand.startsWith("avis") || brand.startsWith("mif1")) {
                return java.util.Optional.of("avif");
            }
        }
        return java.util.Optional.empty();
    }

    private boolean startsWith(byte[] data, byte[] prefix) {
        return regionMatches(data, 0, prefix);
    }

    private boolean regionMatches(byte[] data, int offset, byte[] expected) {
        if (data.length < offset + expected.length) {
            return false;
        }
        return Arrays.equals(data, offset, offset + expected.length, expected, 0, expected.length);
    }
}
